changelog:
  exclude:
    labels:
      - dependencies
      - github-actions
  categories:
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - '*'
